apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-reader-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-reader
  template:
    metadata:
      labels:
        app: secret-reader
    spec:
      serviceAccountName: secret-reader
      containers:
      - name: curl-container
        image: curlimages/curl:latest
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"